# .travis.yml
# Used for Continuous Integration builds on Linux/OS X via https://travis-ci.org
sudo: false
language: c # default is ruby

matrix:
  fast_finish: true
  include:
    # Previous lts releases
    - os: linux
      env: STACK_YAML=stack-ghc-7.8.yaml STACK_PKG_URL=https://github.com/commercialhaskell/stack/releases/download/v1.9.3/stack-1.9.3-linux-x86_64-static.tar.gz
    - os: linux
      env: STACK_YAML=stack-ghc-7.10.yaml STACK_PKG_URL=https://www.stackage.org/stack/linux-x86_64
    - os: linux
      env: STACK_YAML=stack-ghc-8.0.yaml STACK_PKG_URL=https://www.stackage.org/stack/linux-x86_64
    - os: linux
      env: STACK_YAML=stack-ghc-8.2.yaml STACK_PKG_URL=https://www.stackage.org/stack/linux-x86_64
    - os: linux
      env: STACK_YAML=stack-ghc-8.4.yaml STACK_PKG_URL=https://www.stackage.org/stack/linux-x86_64
    # Current releases
    - os: linux
      env: STACK_PKG_URL=https://www.stackage.org/stack/linux-x86_64
    - os: osx
      env: STACK_PKG_URL=https://www.stackage.org/stack/osx-x86_64
    # Nightly
    - os: linux
      env: STACK_YAML=stack-nightly.yaml STACK_PKG_URL=https://www.stackage.org/stack/linux-x86_64

cache:
  directories:
    - $HOME/.stack

before_install:
  - source .ci-scripts/travis/install-stack.sh

# Here starts the actual work to be performed for the package under test;
# any command which exits with a non-zero exit code causes the build to fail.
script:
  - source .ci-scripts/travis/run-hlint.sh
  - travis_wait 45 stack --no-terminal --skip-ghc-check test --flag github-webhooks:ci --haddock --no-haddock-deps
  - source .ci-scripts/travis/run-weeder.sh
