name: github-webhooks-scotty-example
version: 0.0.0
license: MIT
copyright: (c) 2017-2019 ONROCK
author: Kyle Van Berendonck <kyle.vanberendonck@onrock.online>
maintainer: Kyle Van Berendonck <foss@onrock.online>

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates

default-extensions:
  - OverloadedStrings

dependencies:
 - base == 4.*
 - bytestring
 - github-webhooks
 - scotty

executables:
  github-webhooks-scotty-example:
    main: Main.hs
    source-dirs: src
