name: github-webhooks-servant-example
version: 0.0.0
license: MIT
copyright: (c) 2017-2019 ONROCK
author: Kyle Van Berendonck <kyle.vanberendonck@onrock.online>
maintainer: Kyle Van Berendonck <foss@onrock.online>

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates

default-extensions:
  - OverloadedStrings
  - DataKinds
  - TypeFamilies
  - TypeOperators

dependencies:
 - base == 4.*
 - bytestring
 - wai
 - warp
 - github-webhooks
 - servant
 - servant-server
 - servant-github-webhook

executables:
  github-webhooks-servant-example:
    main: Main.hs
    source-dirs: src
